spring:
  profiles:
    active: development

---
spring:
  profiles: development

eureka:
  client:
    region: abc
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl: 
      defaultZone: http://10.1.1.166:8761/eureka/

---
spring:
  profiles: vm
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl: 
      defaultZone: http://172.31.22.222:8761/eureka/
