spring:
  profiles:
    active: development

---
spring:
  profiles: development
   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${EUREKA_SERVER_PORT:8761}/eureka/
    
zuul:
  routes:
    user-service:
      path: /api/user/**
    todo-service:
      url: http://localhost:8082/
      path: /api/todo/**

---
spring:
  profiles: vm
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${EUREKA_SERVER_PORT:8761}/eureka/  

zuul:
  routes:
    user-service:
      path: /api/user/**
    todo-service:
      path: /api/todo/**
