spring:
  profiles:
    active: development

---
spring:
  profiles: development
  rabbitmq:
    host: 10.1.1.166
    port: 5672
    username: guest
    password: guest
   
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.1.1.166:8761/eureka/    
      
zuul:
  routes:
    user-service:
      service-id: user-service 
      path: /api/user/**
    todo-service:
      service-id: todo-service
      path: /api/todo/**
      
todo-service:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100      

---
spring:
  profiles: vm
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.31.22.222:8761/eureka/
      
zuul:
  routes:
    user-service:
      path: /api/user/**
    todo-service:
      path: /api/todo/**
