message: Hello TODO TEST 08.30 Service!!!!

spring:
  profiles:
    active: development

---
spring:
  profiles: development
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${EUREKA_SERVER_PORT:8761}/eureka/

---
spring:
  profiles: vm      

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${EUREKA_SERVER_PORT:8761}/eureka/
