message: Hello TODO TEST 09.08 Service!!!!

spring:
  profiles:
    active: development

---
spring:
  profiles: development
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.1.1.166:8761/eureka/

---
spring:
  profiles: vm      

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${EUREKA_SERVER_PORT:8761}/eureka/
