message: Hello TODO TEST 09.08 Service!!!!

spring:
  profiles:
    active: development

---
spring:
  profiles: development
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.1.1.127:8761/eureka/

---
spring:
  profiles: vm      

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.31.22.222:8761/eureka/
