message: Hello USER TEST Service!!!!

spring:
  profiles:
    active: development

---
spring:
  profiles: development
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${EUREKA_SERVER_PORT:8761}/eureka/

---
spring:
  profiles: vm

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${EUREKA_SERVER_PORT:8761}/eureka/
